### ISSUE TITLE
generated_output in usage_example.py doesn't contain a valid output

### ISSUE THREAD

**Issue by mrcabbage972** [Mivg/SLED#5]
In usage_example.py, generated_output is always equal to the prefix. Or if there's no prefix, it's equal to the document content. I tried it with a few different texts.

**Comment by Mivg** [comment]
Hi,
The model loaded in usage_example.py is the pertained facebook/bart-base model wrapped with SLED. As it was not fine-tuned on anything, it indeed mostly just generates output identical to the input as it was trained to Denise the input. The usage example just gives an example how one can load and generate using a model, you should fine-tune on your task before using it. Alternatively, you can load a fine-tuned SLED checkpoint from the hub. For example, you can try loading BART-base-SLED fine-tuned on contract NLI with `tau/bart-base-sled-contractnli`
